version: '3'
services:
  api_prod:
    image: nuswill/human-nodejs-challange
    working_dir: /app
    env_file: ./.env.prod
    environment:
      - NODE_ENV=production
      - DB_HOST=db_prod
      - DB_USERNAME=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_DB_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - JWT_SECRET=JWT_SECRET
    ports:
      - 3000:3000
    depends_on:
      - db_prod
    stdin_open: true
    tty: true

  db_prod:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env.prod
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ./dockerdb/mount:/var/lib/mysql
